---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Spatial and Temporal Evaluation of Lead Air Pollution Patterns in Pennsylvania"
subtitle: "https://github.com/nyb5208/Alcorn_Bao_Hermanson_ENV_872_EDA_FinalProject.git"
author: "Jack Alcorn, Max Hermanson, and Nancy Bao "
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()
# Load your packages
library(tidyverse)
library(ggplot2)
library(ggridges)
library(ggpubr)
library(plyr)
library(lubridate)
library(zoo)
library(trend)
library(sf)
library(knitr)
library(kableExtra)
#Load color palette packages
library(RColorBrewer)
library(wesanderson)
library(viridisLite)
library(viridis)
library(colormap)

# Set your ggplot theme
project.theme <- theme_classic(base_size=12)+
                 theme(plot.title= 
                         element_text(size=14,
                         face="bold",
                         color= "black",
                         hjust=0.5),
                         axis.text = 
                         element_text(color = "black"),
                         axis.title = 
                         element_text(color= "black",face= "bold"),
                         legend.position="top")
theme_set(project.theme)
# Load EPA Air Lead Pollution datasets
epa.PAlead.2010 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_10_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2011 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_11_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2012 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_12_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2013 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_13_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2014 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_14_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2015 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_15_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2016 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_16_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2017 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_17_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2018 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_18_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2019 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_19_PA_lead.csv", stringsAsFactors = TRUE)
epa.PAlead.2020 <-read.csv( "./Data/Raw/EPA_Lead_PA/EPA_20_PA_lead.csv", stringsAsFactors = TRUE)
# Combined the EPA lead air data sets with rbind()
epa.PAair.lead <-rbind(epa.PAlead.2010, epa.PAlead.2011, epa.PAlead.2012, epa.PAlead.2013,
                       epa.PAlead.2014, epa.PAlead.2015, epa.PAlead.2016, epa.PAlead.2017,
                       epa.PAlead.2018, epa.PAlead.2019, epa.PAlead.2020)

#Change date variable from factor to date
epa.PAair.lead$Date <- as.Date(epa.PAair.lead$Date, format="%m/%d/%Y")
class(epa.PAair.lead$Date)
```


# Rationale and Research Questions



\newpage

# Dataset Information
>US EPA Daily Outdoor Air Quality Data 


\newpage

# Exploratory Analysis 
```{r exploratory-analysis, include= FALSE, warning = FALSE}
#
dim(epa.PAair.lead)
colnames(epa.PAair.lead)
head(epa.PAair.lead)

#Cleaned and Processed EPA PA Air Lead Data

```


\newpage

# Analysis
```{r time_series-analysis}

```

```{r spatial-analysis}

```

## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
