---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Spatial and Temporal Evaluation of Lead Air Pollution Patterns in Pennsylvania"
subtitle: "https://github.com/nyb5208/Alcorn_Bao_Hermanson_ENV_872_EDA_FinalProject.git"
author: "Jack Alcorn, Max Hermanson, and Nancy Bao "
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()
# Load your packages
library(tidyverse)
library(ggplot2)
library(ggridges)
library(ggpubr)
library(plyr)
library(lubridate)
library(zoo)
library(trend)
library(sf)
library(knitr)
library(kableExtra)
#Load color palette packages
library(RColorBrewer)
library(wesanderson)
library(viridisLite)
library(viridis)
library(colormap)

# Set your ggplot theme
project.theme <- theme_classic(base_size=12)+
                 theme(plot.title= 
                         element_text(size=12,
                         face="bold",
                         color= "black",
                         hjust=0.5),
                         axis.text = 
                         element_text(color = "black"),
                         axis.title = 
                         element_text(color= "black",face= "bold"),
                         legend.position="top")
theme_set(project.theme)
# Load your datasets

```


# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 
```{r exploratory-analysis}

```


\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
